### ISSUE TITLE
Any example or demo here ? I am getting require is not defined.

### ISSUE THREAD

**Issue by minchemo** [Collaborne/cordova-gallery-access#10]
I am using this plugin on cordova to setup a gallery app , installed gallery-api and cordova-gallery-access.

Always getting require is not defined if I called function , anyone can help me out ?

> Cordova 8.1.1

**Comment by ankon** [comment]
I think your question is something where stackoverflow.com would be a more suitable forum for. It sounds like your problem isn't with this library, but rather with your general infrastructure and the way you build the application.

**Comment by minchemo** [comment]
yes, sorry about that .
I fixed it , its my application setting issue,  work perfectly now.
