### ISSUE TITLE
Working with UIWebView ?

### ISSUE THREAD

**Issue by ThomasKientz** [Collaborne/cordova-gallery-access#2]
Hi, 

Is this plugin working with an old UIWebWiew (not WKWebView) ? 

Since you're talking about the hard time you had with WKWebView, just wanna be sure its working with the old UIWebView before trying this plugin. 

Thanks a lot

**Comment by ronnyroeller** [comment]
Hi Thomas, I don't know. We only use it with WKWebView. In case you try it out, please let me know, and I can add to the documentation here.

**Comment by ThomasKientz** [comment]
Ionic just release a new version of WKWebView, so i'm switching to it :)
