### ISSUE TITLE
CdvToken & local-filesystem trick

### ISSUE THREAD

**Issue by dorianrod** [Collaborne/cordova-gallery-access#7]
Hi,

I've read your blog posts, thanks for sharing it and open sourced your code. I'm totally stucked with the same issues your encountered on ios :  I can't display my pictures in a WKWebView.

I yet use a library for permissions request and gettings phone pictures and i try to use the trick you explain in your blog post : the url to use for img should be "/local-filesystem${item.thumbnail}?cdvToken=${cdvToken}". I don't see in your plugin code, neither in  cordova-gallery-api where cdvToken is used. I don't get how the local webserver translate this url to something linked to the picture. Is it done by wkwebview or local server plugin ?

My questions :
- How do I know the parameter cdvToken to use for a picture ?
- Is URL should be something like /local-filesystem/var/mobile/Media/DCIM/100APPLE/IMG_0002.JPG?cdvToken=550149E3-35DA-43C8-89E7-D169D0CE8597%2FL0%2F001 ?

Have a great day

Dorian

**Comment by ronnyroeller** [comment]
Hi Dorian,
It has been a while since I worked on this stuff.
Here is what I recall:

> How do I know the parameter cdvToken to use for a picture ?

As far as I recall, Cordova’s local webserver plugin adds the cdvToken to your index.html as a parameter (e.g. index.html?cdvToken=xyz). You can then just pick from the URL.

> Is URL should be something like /local-filesystem/var/mobile/Media/DCIM/100APPLE/IMG_0002.JPG?cdvToken=550149E3-35DA-43C8-89E7-D169D0CE8597%2FL0%2F001

I think you need to use a relative URL (this is passed over the local webserver) - your URL looks more like an internal file path. I don't remember the exact URL format but it should be something like `/img/...` (not a file path).
Check the documentation of the local webserver for more details: https://github.com/ankon/cordova-plugins/tree/master-collaborne/local-webserver

**Comment by dorianrod** [comment]
Ok, thanks for your answer. 
I've checked the local webserver documentatiton but the first thing they say is "will serve the contents of your www directory, looking for an index page of index.html", that's why i don't get how the path local-filesystem/ can help to reach a picture.

Well, that's totally obscur for me, i would really need a more detailed example. Do i only need to install this local webserver and wkwebview plugins to make everything works or I only need to install your cordova-gallery-api plugin ?

**Comment by ankon** [comment]
The `/local-filesystem/` is provided by the local-webserver plugin: https://github.com/ankon/cordova-plugins/blob/master-collaborne/local-webserver/src/ios/CDVLocalWebServer.m#L295

So the approach is to 
1. Use the local-webserver
2. Transform any paths you get from enumerating the gallery from their `/var/mobile/...` representation to `/local-filesystem/var/mobile/...?cdvToken=...`.

The browser will take the `/local-filesystem/` reference, resolve it against the origin (the `http://localhost:PORT` of where the local webserver is running and where your index.html was loaded from), and the local-webserver will then fetch the content for you.

I hope this makes a bit sense.
