### ISSUE TITLE
getMedia never resolving nor rejecting the promise in iOS

### ISSUE THREAD

**Issue by giacomodeliberali** [Collaborne/cordova-gallery-access#8]
The `getMedia`method is never resolving nor rejecting the promise. Works fine in Android, the issue occurs only in iOS (tested in 11.4). 
```
// getMedia(album)
return new Promise((resolve, reject) => {
    galleryApi.getMedia(
        album,
        items => resolve(items),
        e => reject(`Failed to load items for album ${album.id}: ${e}`)
    );
});
```
I inspected the [code](https://github.com/SuryaL/cordova-gallery-api/blob/master/src/ios/GalleryAPI.m), but found nothing relevant. Anyone has the same issue?

**Comment by changliu86** [comment]
I did experience the same problem you described. Does anyone have a solution on this ? 
The plugin works fine on Android. But it doesn't work on IOS, and there is no error in the debugger

**Comment by ronnyroeller** [comment]
The `cordova-gallery-access` library is only a wrapper of `cordova-gallery-api`.
Best to debug what the method `galleryApi.getMedia` does. If you can localize the issue there, best file a ticket with the underlying library: https://github.com/SuryaL/cordova-gallery-api
